#!/usr/bin/env python3
"""Report what the catalog holds, and keep the documented counts honest.

    python3 tools/coverage.py            # print the current state
    python3 tools/coverage.py --write    # regenerate the tables in the docs
    python3 tools/coverage.py --check    # fail if a documented table is stale

Counts in prose go stale the moment anything is generated, and a stale count in a
document that exists to be trusted is worse than no count at all. The tables live
between markers and are written from the committed objects, so the number in the
README is the number in the repository by construction rather than by discipline.
"""

import argparse
import collections
import glob
import json
import pathlib
import re
import sys

START = "<!-- coverage:{}:start -->"
END = "<!-- coverage:{}:end -->"

SOURCES = [
    ("AICM 1.1.0 controls", "generate_aicm_controls.py",
     lambda o: o["type"] == "x-control" and o.get("framework") == "aicm"),
    ("AI-CAIQ 1.1.0 questions", "generate_aicm_caiq.py",
     lambda o: o["type"] == "x-control" and o.get("framework") == "aicm-caiq"),
    ("EU AI Act provisions", "generate_aicm_eu_mappings.py",
     lambda o: o["type"] == "x-regulation"),
    ("Cited standards (BSI AIC4/C5, ISO 42001/27001/27002)",
     "generate_aicm_standard_mappings.py",
     lambda o: o["type"] == "x-control"
     and o.get("framework_namespace") in ("bsi.bund.de", "iso.org")),
]


def objects():
    for path in sorted(glob.glob("objects/**/*.json", recursive=True)):
        yield json.load(open(path))


def quarantines():
    for path in sorted(glob.glob("quarantine/*.json")):
        yield path, json.load(open(path))


def catalog_table():
    objs = list(objects())
    rows = [("| Content | Objects | Generated by |"), ("|---|---|---|")]
    for label, tool, match in SOURCES:
        n = sum(1 for o in objs if match(o))
        rows.append(f"| {label} | {n} | [`tools/{tool}`](../tools/{tool}) |")
    links = sum(1 for o in objs if o.get("relationship_type") == "derived-from")
    verdicts = sum(1 for o in objs if o["type"] == "x-gap-mapping")
    rows.append(f"| Question-to-control links (`derived-from`) | {links} | — |")
    rows.append(f"| Coverage verdicts (`x-gap-mapping`) | {verdicts} | — |")
    rows.append(f"| **Total committed objects** | **{len(objs)}** | |")
    return "\n".join(rows)


def summary_table():
    counts = collections.Counter(o["type"] for o in objects())
    rows = ["| STIX type | Objects |", "|---|---|"]
    for t, n in sorted(counts.items(), key=lambda kv: -kv[1]):
        rows.append(f"| `{t}` | {n} |")
    rows.append(f"| **Total** | **{sum(counts.values())}** |")
    return "\n".join(rows)


def quarantine_table():
    rows = ["| File | Source column | Mapped | Held |", "|---|---|---|---|"]
    for path, q in quarantines():
        name = pathlib.Path(path).name
        column = q["source"].split("scope_applicability_mappings.")[-1]
        rows.append(f"| [`{name}`]({name}) | `{column}` | {q['controls_mapped']} "
                    f"| **{q['controls_held']}** |")
    return "\n".join(rows)


BLOCKS = {
    "README.md": {"summary": summary_table},
    "objects/README.md": {"catalog": catalog_table},
    "quarantine/README.md": {"files": quarantine_table},
}


def apply(write):
    stale = []
    for path, blocks in BLOCKS.items():
        text = pathlib.Path(path).read_text()
        original = text
        for name, build in blocks.items():
            start, end = START.format(name), END.format(name)
            pattern = re.compile(re.escape(start) + r".*?" + re.escape(end), re.S)
            if not pattern.search(text):
                sys.exit(f"{path}: no {name} coverage markers")
            text = pattern.sub(f"{start}\n{build()}\n{end}", text)
        if text != original:
            stale.append(path)
            if write:
                pathlib.Path(path).write_text(text)
    return stale


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true", help="regenerate the tables")
    ap.add_argument("--check", action="store_true", help="fail if any table is stale")
    args = ap.parse_args(argv)

    if args.write or args.check:
        stale = apply(args.write)
        if args.check and stale:
            print("stale coverage tables: " + ", ".join(stale))
            print("run: python3 tools/coverage.py --write")
            return 1
        print("updated: " + ", ".join(stale) if stale else "coverage tables current")
        return 0

    print(summary_table(), "\n")
    print(catalog_table(), "\n")
    print(quarantine_table())
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
